/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUserIdentityNFT,
  IUserIdentityNFTInterface,
} from "../../../contracts/interfaces/IUserIdentityNFT";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "userAddres",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "MintNft",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "userAddres",
        type: "address",
      },
    ],
    name: "Redeem",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "uri",
            type: "string",
          },
          {
            internalType: "bytes",
            name: "userId",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "fingerPrint",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct UserIdVoucher",
        name: "voucher",
        type: "tuple",
      },
    ],
    name: "createSingleNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "uri",
            type: "string",
          },
          {
            internalType: "bytes",
            name: "userId",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "fingerPrint",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct UserIdVoucher[]",
        name: "voucher",
        type: "tuple[]",
      },
    ],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUserIdentityNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IUserIdentityNFTInterface {
    return new utils.Interface(_abi) as IUserIdentityNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUserIdentityNFT {
    return new Contract(address, _abi, signerOrProvider) as IUserIdentityNFT;
  }
}
